#! /usr/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  my $is_same_dir = $^O eq 'MSWin32' ? (Win32::GetShortPathName($curdir) eq '/home/book/sources/perl/CPAN/Acme-MetaSyntactic')
                                       : ($curdir eq '/home/book/sources/perl/CPAN/Acme-MetaSyntactic');
  unless ($is_same_dir) {
    die ('This script must be run from /home/book/sources/perl/CPAN/Acme-MetaSyntactic, not '.$curdir."\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/home/book/sources/perl',
     '/home/book/bin/perl',
     '/etc/perl',
     '/usr/local/lib/perl/5.8.4',
     '/usr/local/share/perl/5.8.4',
     '/usr/lib/perl5',
     '/usr/share/perl5',
     '/usr/lib/perl/5.8',
     '/usr/share/perl/5.8',
     '/usr/local/lib/site_perl',
     '/home/book/sources/perl/CPAN/Acme-MetaSyntactic'
    );
}

use Module::Build;

if (-e 'Build.PL' and not Module::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '/home/book/sources/perl/CPAN/Acme-MetaSyntactic/_build',
  },
);

$build->dispatch;
