---
abstract: 'Themed metasyntactic variables names'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-MetaSyntactic
provides:
  Acme::MetaSyntactic:
    file: lib/Acme/MetaSyntactic.pm
    version: 1.008
  Acme::MetaSyntactic::Alias:
    file: lib/Acme/MetaSyntactic/Alias.pm
    version: 1.000
  Acme::MetaSyntactic::List:
    file: lib/Acme/MetaSyntactic/List.pm
    version: 1.001
  Acme::MetaSyntactic::Locale:
    file: lib/Acme/MetaSyntactic/Locale.pm
    version: 1.000
  Acme::MetaSyntactic::MultiList:
    file: lib/Acme/MetaSyntactic/MultiList.pm
    version: 1.000
  Acme::MetaSyntactic::RemoteList:
    file: lib/Acme/MetaSyntactic/RemoteList.pm
    version: 1.003
  Acme::MetaSyntactic::any:
    file: lib/Acme/MetaSyntactic/any.pm
    version: 1.000
  Acme::MetaSyntactic::contributors:
    file: lib/Acme/MetaSyntactic/contributors.pm
    version: 1.001
  Acme::MetaSyntactic::foo:
    file: lib/Acme/MetaSyntactic/foo.pm
    version: 1.001
  Test::MetaSyntactic:
    file: lib/Test/MetaSyntactic.pm
    version: 1.003
  eta:
    file: lib/eta.pm
    version: 1.001
recommends:
  LWP::UserAgent: 5.802
requires:
  File::Glob: 0
  List::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/Acme-MetaSyntactic
version: 1.008
