--- #YAML:1.0
name: Acme-MetaSyntactic
version: 0.87
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: Themed metasyntactic variables names
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
