--- #YAML:1.0
name:               Acme-MetaSyntactic
version:            0.99_03
abstract:           Themed metasyntactic variables names
author:
    - Philippe "BooK" Bruhat <book@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Glob:  0
    List::Util:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
