--- #YAML:1.0
name: Acme-MetaSyntactic
version: 0.05
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: Themed metasyntactic variables names
license: perl
requires:
  List::Util: 0
  Test::More: 0
provides:
  Acme::MetaSyntactic:
    file: lib/Acme/MetaSyntactic.pm
    version: 0.05
generated_by: Module::Build version 0.26
