---
name: Acme-MetaSyntactic
version: 0.45
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: Themed metasyntactic variables names
license: perl
requires:
  File::Glob: 0
  List::Util: 0
  Test::More: 0
provides:
  Acme::MetaSyntactic:
    file: lib/Acme/MetaSyntactic.pm
    version: 0.45
  'Acme::MetaSyntactic::':
    file: lib/Acme/MetaSyntactic.pm
    version: 0.45
  Acme::MetaSyntactic::List:
    file: lib/Acme/MetaSyntactic/List.pm
  Acme::MetaSyntactic::Locale:
    file: lib/Acme/MetaSyntactic/Locale.pm
  Acme::MetaSyntactic::alphabet:
    file: lib/Acme/MetaSyntactic/alphabet.pm
  Acme::MetaSyntactic::amber:
    file: lib/Acme/MetaSyntactic/amber.pm
  Acme::MetaSyntactic::any:
    file: lib/Acme/MetaSyntactic/any.pm
  Acme::MetaSyntactic::apollo:
    file: lib/Acme/MetaSyntactic/apollo.pm
  Acme::MetaSyntactic::batman:
    file: lib/Acme/MetaSyntactic/batman.pm
  Acme::MetaSyntactic::booze:
    file: lib/Acme/MetaSyntactic/booze.pm
  Acme::MetaSyntactic::browser:
    file: lib/Acme/MetaSyntactic/browser.pm
  Acme::MetaSyntactic::buffy:
    file: lib/Acme/MetaSyntactic/buffy.pm
  Acme::MetaSyntactic::constellations:
    file: lib/Acme/MetaSyntactic/constellations.pm
  Acme::MetaSyntactic::counting_rhyme:
    file: lib/Acme/MetaSyntactic/counting_rhyme.pm
  Acme::MetaSyntactic::crypto:
    file: lib/Acme/MetaSyntactic/crypto.pm
  Acme::MetaSyntactic::currency:
    file: lib/Acme/MetaSyntactic/currency.pm
  Acme::MetaSyntactic::dancers:
    file: lib/Acme/MetaSyntactic/dancers.pm
  Acme::MetaSyntactic::debian:
    file: lib/Acme/MetaSyntactic/debian.pm
  Acme::MetaSyntactic::dilbert:
    file: lib/Acme/MetaSyntactic/dilbert.pm
  Acme::MetaSyntactic::discworld:
    file: lib/Acme/MetaSyntactic/discworld.pm
  Acme::MetaSyntactic::donmartin:
    file: lib/Acme/MetaSyntactic/donmartin.pm
  Acme::MetaSyntactic::elements:
    file: lib/Acme/MetaSyntactic/elements.pm
  Acme::MetaSyntactic::flintstones:
    file: lib/Acme/MetaSyntactic/flintstones.pm
  Acme::MetaSyntactic::foo:
    file: lib/Acme/MetaSyntactic/foo.pm
  Acme::MetaSyntactic::garbage:
    file: lib/Acme/MetaSyntactic/garbage.pm
  Acme::MetaSyntactic::groo:
    file: lib/Acme/MetaSyntactic/groo.pm
  Acme::MetaSyntactic::haddock:
    file: lib/Acme/MetaSyntactic/haddock.pm
  Acme::MetaSyntactic::hhgg:
    file: lib/Acme/MetaSyntactic/hhgg.pm
  Acme::MetaSyntactic::jamesbond:
    file: lib/Acme/MetaSyntactic/jamesbond.pm
  Acme::MetaSyntactic::jerkcity:
    file: lib/Acme/MetaSyntactic/jerkcity.pm
  Acme::MetaSyntactic::loremipsum:
    file: lib/Acme/MetaSyntactic/loremipsum.pm
  Acme::MetaSyntactic::magic8ball:
    file: lib/Acme/MetaSyntactic/magic8ball.pm
  Acme::MetaSyntactic::magicroundabout:
    file: lib/Acme/MetaSyntactic/magicroundabout.pm
  Acme::MetaSyntactic::monty_spam:
    file: lib/Acme/MetaSyntactic/monty_spam.pm
  Acme::MetaSyntactic::octothorpe:
    file: lib/Acme/MetaSyntactic/octothorpe.pm
  Acme::MetaSyntactic::oulipo:
    file: lib/Acme/MetaSyntactic/oulipo.pm
  Acme::MetaSyntactic::pasta:
    file: lib/Acme/MetaSyntactic/pasta.pm
  Acme::MetaSyntactic::peanuts:
    file: lib/Acme/MetaSyntactic/peanuts.pm
  Acme::MetaSyntactic::phonetic:
    file: lib/Acme/MetaSyntactic/phonetic.pm
  Acme::MetaSyntactic::pumpkings:
    file: lib/Acme/MetaSyntactic/pumpkings.pm
  Acme::MetaSyntactic::punctuation:
    file: lib/Acme/MetaSyntactic/punctuation.pm
  Acme::MetaSyntactic::pynchon:
    file: lib/Acme/MetaSyntactic/pynchon.pm
  Acme::MetaSyntactic::python:
    file: lib/Acme/MetaSyntactic/python.pm
  Acme::MetaSyntactic::quantum:
    file: lib/Acme/MetaSyntactic/quantum.pm
  Acme::MetaSyntactic::robin:
    file: lib/Acme/MetaSyntactic/robin.pm
  Acme::MetaSyntactic::roman:
    file: lib/Acme/MetaSyntactic/roman.pm
  Acme::MetaSyntactic::services:
    file: lib/Acme/MetaSyntactic/services.pm
  Acme::MetaSyntactic::shadok:
    file: lib/Acme/MetaSyntactic/shadok.pm
  Acme::MetaSyntactic::simpsons:
    file: lib/Acme/MetaSyntactic/simpsons.pm
  Acme::MetaSyntactic::stars:
    file: lib/Acme/MetaSyntactic/stars.pm
  Acme::MetaSyntactic::teletubbies:
    file: lib/Acme/MetaSyntactic/teletubbies.pm
  Acme::MetaSyntactic::tld:
    file: lib/Acme/MetaSyntactic/tld.pm
  Acme::MetaSyntactic::toto:
    file: lib/Acme/MetaSyntactic/toto.pm
  Acme::MetaSyntactic::viclones:
    file: lib/Acme/MetaSyntactic/viclones.pm
  Acme::MetaSyntactic::yapc:
    file: lib/Acme/MetaSyntactic/yapc.pm
generated_by: Module::Build version 0.26
